version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "buildercreed"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d396kbqfopbz"
s3_prefix = "buildercreed"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
